name: 'Release Updates to Google Artifact Registry'

on:
  workflow_dispatch:
  push: 
    tags: 
      - '*' # Workflow is trigered when a push is made with a tag
jobs:
  # Job 1: Check that the release version is correct
  well-tag-triggered-job:
    name: 'Check tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      TZ: Europe/Madrid  # Set the timezone to your local timezone
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Step 1: Clone the source repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Display tag information
      - name: Get Tag Details
        run: |
          echo "Tag Name: ${{ github.ref_name }}"
          echo "Full Reference: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"

          ## Changing the variable name for the tag
          echo "tag=${{github.ref_name}}">>$GITHUB_ENV
          echo "The Tag name is ${{env.tag}}"

          ## Getting the repository name
          repo_name="${{ github.repository }}"
          echo "repo_name=$repo_name" >> $GITHUB_ENV

      # Step 3: Validate the Tag Format (Date and Commit SHA)
      - name: Validate the Tag Format (Date and Commit SHA)
        run: |
          # Extracting the current date in YYYY.MM.DD format
          current_date=$(date -u +"%Y.%m.%d")  # ✅ Fixed date format
          echo "Current Date: $current_date"

          # Extract commit hash of HEAD
          commit_hash=$(git rev-parse --short HEAD)
          echo "Current Commit Hash: $commit_hash"

          # Extract date and commit from the tag
          tag="${{ env.tag }}"  # ✅ Ensure env variable reference is correct
          echo "Validating Tag: $tag"

          # ✅ Regex to check tag format: vYYYY.MM.DD-shaabcdefg
          if [[ "$tag" =~ ^v([0-9]{4}\.[0-9]{2}\.[0-9]{2})\-sha.([a-f0-9]+)$ ]]; then
            tag_date="${BASH_REMATCH[1]}"
            tag_commit="${BASH_REMATCH[2]}"

            echo "Extracted Tag Date: $tag_date"
            echo "Extracted Tag Commit Hash: $tag_commit"

            # Compare extracted date with current :
            if [[ "$tag_date" != "$current_date" ]]; then
              echo "❌ ERROR: Tag date ($tag_date) does not match today's date ($current_date)!"
              exit 1
            fi

            # Compare extracted commit hash with actual commit hash
            if [[ "$tag_commit" != "$commit_hash" ]]; then
              echo "❌ ERROR: Tag commit hash ($tag_commit) does not match the current commit ($commit_hash)!"
              exit 1
            fi

            echo "✅ Tag validation successful!"
          else
            echo "❌ ERROR: Tag format is incorrect! Expected format: vYYYY.MM.DD-shaabcdefg"
            exit 1
          fi

  # Job 2: Job for uploading a release to GitHub and an artifact to GAR
  uploading-release-to-GitHub-and-GAR:
    name: 'Making release to GitHub and GAR'
    runs-on: ubuntu-latest
    needs: well-tag-triggered-job
    permissions:
      contents: write
      id-token: write
    env:
      TZ: Europe/Madrid  # Set the timezone to your local timezone
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps: 

      # Step 1: Clone the source repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2 : Configure Go for Private Modules
      - name: Simulating that some testings and checks are done
        run: |
          # Getting the tag name
          echo "tag=${{github.ref_name}}">>$GITHUB_ENV
          echo "Simulating that some testings and checks are done"

          ## Getting the repository name
          repo_name=$(basename "${{ github.repository }}")
          echo "repo_name=$repo_name" >> $GITHUB_ENV

      # Step 3: Create the ZIP file once and store it
      - name: Prepare ZIP file for release
        run: |
          mkdir -p release
          zip -r "${{ env.repo_name }}.zip" bin/${{ env.repo_name }} config/
          echo "zip_name=${{ env.repo_name }}.zip" >> $GITHUB_ENV

      # Step 4: Compute and save SHA256 of original ZIP (before any upload)
      - name: Compute SHA256 of Original ZIP
        run: |
          sha256sum "release/${{ env.zip_name }}" | tee release.sha256
          digest=$(awk '{ print $1 }' release.sha256)
          echo "digest=$digest" >> $GITHUB_ENV
          echo "Original SHA256: $digest"

      # Step 6: Create GitHub Release
      - name: Create a GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.tag }}
          release_name: "${{ env.repo_name }} ${{ env.tag }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Release generated by GitHub Actions.
          draft: false
          prerelease: false

      # Step 7: Upload ZIP to GitHub Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.zip_name }}
          asset_name: ${{ env.zip_name }}
          asset_content_type: application/zip
      # Step 8: Authenticate with Google Cloud (using Workload Identity Federation)
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/185640679849/locations/global/workloadIdentityPools/github/providers/github-prov
          service_account: github-actions-auth@polished-medium-445107-i9.iam.gserviceaccount.com
          access_token_lifetime: '600s'
      # Step 9: Setting environment variables
      - name: Set Environment Variables
        run: |
          echo "Setting environment variables..."
          echo "service_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)" >> $GITHUB_ENV

      # Step 10: Upload artifact to Google Artifact Registry
      - name: Upload artifacts from bin to Google Artifact Registry
        id: pushing-GAR
        run: |
          echo "Uploading each built artifact to Google Artifact Registry..."
          echo "Uploading service name ${{ env.service_name }}"
          echo "Original version: ${{ env.tag }}"

          gcloud artifacts generic upload \
            --repository=nebula-storage \
            --location=europe-southwest1 \
            --project=polished-medium-445107-i9 \
            --package="${{ env.service_name }}" \
            --version="${{ env.tag }}" \
            --source="${{ env.zip_name }}"

      # Step 11: Getting the SHA of the uploaded file to GAR
      - name: Getting the SHA of the uploaded file to GAR
        id: getting-GAR-digest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Create GAR directory
          mkdir -p GAR
          echo "Downloading artifact from Google Artifact Registry..."

          # Download the artifact from Google Artifact Registry
          gcloud artifacts files download \
            --project=polished-medium-445107-i9 \
            --location=europe-southwest1 \
            --repository=nebula-storage \
            --destination=./GAR/ \
            "${{ env.service_name }}:${{ env.tag }}:${{ env.zip_name }}" \
            --verbosity=debug

          # Detect the actual downloaded filename
          downloaded_file=$(ls -1 GAR/ | head -n 1)  # Get the first file in GAR/
          
          if [ -z "$downloaded_file" ]; then
              echo "Error: No file found in GAR/ after download."
              exit 1
          fi

          # Fix potential encoding issue (%3A instead of ":")
          decoded_file=$(echo "$downloaded_file" | sed 's/%3A/:/g')

          # Rename the file if needed
          if [[ "$downloaded_file" != "$decoded_file" ]]; then
              mv "GAR/$downloaded_file" "GAR/$decoded_file"
              downloaded_file="$decoded_file"
          fi

          # Ensure file is named correctly for SHA256 computation
          final_zip_path="GAR/${{ env.zip_name }}"
          mv "GAR/$downloaded_file" "$final_zip_path"

          echo "Downloaded ZIP file from GAR: $final_zip_path"

          # Compute SHA256 of the downloaded ZIP file
          echo "Computing SHA256 of the downloaded ZIP..."
          gar_downloaded_sha256=$(sha256sum "$final_zip_path" | awk '{ print $1 }')

          if [ -z "$gar_downloaded_sha256" ]; then
              echo "Error: Failed to compute SHA256 of the downloaded ZIP"
              exit 1
          fi

          echo "GAR Downloaded ZIP SHA256: $gar_downloaded_sha256"
          echo "gar_sha256=$gar_downloaded_sha256" >> $GITHUB_ENV

      # Step 12: Download file from GitHub to ./github/ and compute SHA256
      - name: Download and SHA256 from GitHub Release
        run: |
          mkdir -p github

          ASSET_URL=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.tag }}" \
            | jq -r --arg ZIP_NAME "${{ env.zip_name }}" '.assets[] | select(.name == $ZIP_NAME) | .browser_download_url')

          if [ -z "$ASSET_URL" ] || [ "$ASSET_URL" == "null" ]; then
            echo "❌ Asset not found"
            exit 1
          fi

          curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -o "github/${{ env.zip_name }}" "$ASSET_URL"
          sha256sum "github/${{ env.zip_name }}" | tee github.sha256
          github_digest=$(awk '{ print $1 }' github.sha256)
          echo "github_release_sha256=$github_digest" >> $GITHUB_ENV

      # Step 13: Verify SHA256 match
      - name: Compare SHA256 Digests
        run: |
          echo "🔍 GAR SHA256: ${{ env.gar_sha256 }}"
          echo "🔍 GitHub SHA256: ${{ env.github_release_sha256 }}"
          echo "🔍 Original ZIP SHA256: ${{ env.digest }}"

          if [[ "${{ env.gar_sha256 }}" != "${{ env.github_release_sha256 }}" ]]; then
            echo "❌ SHA256 mismatch between GitHub and GAR"
            exit 1
          fi

          if [[ "${{ env.gar_sha256 }}" != "${{ env.digest }}" ]]; then
            echo "❌ GAR artifact differs from original ZIP"
            exit 1
          fi

          echo "✅ All SHA256 checks match. Uploads verified."

